# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MemHooks": "00_core.ipynb",
         "plot_log": "00_core.ipynb",
         "reset_grad": "00_core.ipynb",
         "memprofile": "00_core.ipynb",
         "MemProfileCallback": "00_core.ipynb",
         "Learner.profile_memory": "00_core.ipynb",
         "MemStatsCallback": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://arampacha.github.io/pt_memprofile/"

git_url = "https://github.com/arampacha/pt_memprofile/tree/master/"

def custom_doc_links(name): return None
